<?php
include 'DBConfig.php';


if ($conn->connect_error) {
 
 die("Connection failed: " . $conn->connect_error);
} 


$json = file_get_contents('php://input');
// $items = json_encode($json); 
 
$items ='{
    "data": [{
        "STOCK_ID": "206",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "20",
        "STOCK_QUANTITY": "20",
        "STOCK_KEY_UNIT": "SP-A-0007",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Blower motor with fan",
        "STOCK_SIZE": "12 x 4 inches diameter",
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "NULL",
        "SUP_NAME": "Tastic/Ronnie Metal Works",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "210",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "4",
        "STOCK_QUANTITY": "4",
        "STOCK_KEY_UNIT": "SP-A-0012",
        "STOCK_MODEL": "141 A",
        "STOCK_NAME": "Aircon cleaner with flushing ",
        "STOCK_SIZE": "2 ft x 10 inch diameter",
        "UNIT_TYPE": "small drum",
        "CON_NAME": "NULL",
        "SUP_NAME": "Tastic",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "211",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "12",
        "STOCK_QUANTITY": "50",
        "STOCK_KEY_UNIT": "SP-A-0013",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Imcarate-cleaner",
        "STOCK_SIZE": "1 liter",
        "UNIT_TYPE": "cleaner",
        "CON_NAME": "NULL",
        "SUP_NAME": "Tastic",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#f9f9f98c",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "212",
        "STOCK_BRAND": "Denso",
        "STOCK_CRITICAL_LEVEL": "3",
        "STOCK_QUANTITY": "3",
        "STOCK_KEY_UNIT": "SP-A-0014",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Expansion bulb",
        "STOCK_SIZE": "4 inches",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "NULL",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "214",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "10",
        "STOCK_QUANTITY": "10",
        "STOCK_KEY_UNIT": "SP-A-0016",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Adjuster Pulley",
        "STOCK_SIZE": "1x2 inch length",
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "NULL",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "218",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "1",
        "STOCK_QUANTITY": "1",
        "STOCK_KEY_UNIT": "SP-A-0021",
        "STOCK_MODEL": "GP",
        "STOCK_NAME": "Radiator",
        "STOCK_SIZE": "2 ft x 4 ft",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "NULL",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "219",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "1",
        "STOCK_QUANTITY": "1",
        "STOCK_KEY_UNIT": "SP-A-0022",
        "STOCK_MODEL": "SP",
        "STOCK_NAME": "Radiator",
        "STOCK_SIZE": "2 ft x 4 ft",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "NULL",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": true,
        "qty": "45",
        "suppid": "5"
    }, {
        "STOCK_ID": "225",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "3",
        "STOCK_QUANTITY": "3",
        "STOCK_KEY_UNIT": "SP-A-0028",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Air Compressor Head",
        "STOCK_SIZE": "1/2 kilo/4 diameter",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "NULL",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": true,
        "qty": "45",
        "suppid": "5"
    }, {
        "STOCK_ID": "257",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "4",
        "STOCK_QUANTITY": "4",
        "STOCK_KEY_UNIT": "SP-A-0062",
        "STOCK_MODEL": "SP",
        "STOCK_NAME": "Hydro back",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "repair kit",
        "CON_NAME": "NULL",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "258",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "10",
        "STOCK_QUANTITY": "10",
        "STOCK_KEY_UNIT": "SP-A-0064",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Air Governor",
        "STOCK_SIZE": "1.5 diameter/4 inches width",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "NULL",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": true,
        "qty": "23",
        "suppid": "9"
    }, {
        "STOCK_ID": "282",
        "STOCK_BRAND": "N150",
        "STOCK_CRITICAL_LEVEL": "5",
        "STOCK_QUANTITY": "5",
        "STOCK_KEY_UNIT": "SP-A-0090",
        "STOCK_MODEL": null,
        "STOCK_NAME": "12 volts",
        "STOCK_SIZE": "5 pairs",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "NULL",
        "SUP_NAME": "CRC Enterprises",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "200",
        "STOCK_BRAND": "Bando",
        "STOCK_CRITICAL_LEVEL": "10",
        "STOCK_QUANTITY": "20",
        "STOCK_KEY_UNIT": "SP-A-0001",
        "STOCK_MODEL": "PKB/SP",
        "STOCK_NAME": "Fanbelt (Plain)",
        "STOCK_SIZE": "B71 ",
        "UNIT_TYPE": "5480/Evico",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Jecara/Miguel",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#f9f9f98c",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "201",
        "STOCK_BRAND": "Bando",
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0002",
        "STOCK_MODEL": "JP/back engine",
        "STOCK_NAME": "Fanbelt (Plain)",
        "STOCK_SIZE": "B74",
        "UNIT_TYPE": "5590",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Jecara/Miguel",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "203",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "10",
        "STOCK_QUANTITY": "10",
        "STOCK_KEY_UNIT": "SP-A-0004",
        "STOCK_MODEL": "Surplus",
        "STOCK_NAME": "Compressor",
        "STOCK_SIZE": "4 inches in diameter",
        "UNIT_TYPE": "Square Head",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Denso/Nick Store",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "204",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "10",
        "STOCK_QUANTITY": "10",
        "STOCK_KEY_UNIT": "SP-A-0005",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Discharge hose",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "Local",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Rodrigo Hydraulic",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "205",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "10",
        "STOCK_QUANTITY": "10",
        "STOCK_KEY_UNIT": "SP-A-0006",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Suction hose",
        "STOCK_SIZE": "4x2 ft",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Tastic",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "207",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "10",
        "STOCK_QUANTITY": "10",
        "STOCK_KEY_UNIT": "SP-A-0008",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Magnetic Clutch",
        "STOCK_SIZE": "4 x 1 inch diameter",
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Tastic/Ronnie Metal Works",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "208",
        "STOCK_BRAND": "Denso",
        "STOCK_CRITICAL_LEVEL": "10",
        "STOCK_QUANTITY": "30",
        "STOCK_KEY_UNIT": "SP-A-0010",
        "STOCK_MODEL": null,
        "STOCK_NAME": "High pressure switch",
        "STOCK_SIZE": "1 x 1 meter",
        "UNIT_TYPE": "with sensor",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#f9f9f98c",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "209",
        "STOCK_BRAND": "Denso",
        "STOCK_CRITICAL_LEVEL": "10",
        "STOCK_QUANTITY": "10",
        "STOCK_KEY_UNIT": "SP-A-0011",
        "STOCK_MODEL": null,
        "STOCK_NAME": "High pressure switch",
        "STOCK_SIZE": "1 x 1 meter",
        "UNIT_TYPE": "with resistor",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "213",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "150",
        "STOCK_QUANTITY": "150",
        "STOCK_KEY_UNIT": "SP-A-0015",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Carbon brush",
        "STOCK_SIZE": "1 inch length",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Punzalan",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "215",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "200",
        "STOCK_QUANTITY": "200",
        "STOCK_KEY_UNIT": "SP-A-0017",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Air Vent",
        "STOCK_SIZE": "2 inches diameter",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Nick Metal Work",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "220",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "10",
        "STOCK_QUANTITY": "10",
        "STOCK_KEY_UNIT": "SP-A-0023",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Upper Hose",
        "STOCK_SIZE": "2 inches x 1.5 diameter",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "221",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "10",
        "STOCK_QUANTITY": "10",
        "STOCK_KEY_UNIT": "SP-A-0024",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Lower Hose",
        "STOCK_SIZE": "2 inches x 1.5 diameter",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "222",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "10",
        "STOCK_QUANTITY": "10",
        "STOCK_KEY_UNIT": "SP-A-0025",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Thermostat",
        "STOCK_SIZE": "2.5 diameter",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "223",
        "STOCK_BRAND": "FE6-Nissan",
        "STOCK_CRITICAL_LEVEL": "1",
        "STOCK_QUANTITY": "1",
        "STOCK_KEY_UNIT": "SP-A-0026",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Steering pump",
        "STOCK_SIZE": "1 kilo",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "224",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0027",
        "STOCK_MODEL": "SP",
        "STOCK_NAME": "Water pump",
        "STOCK_SIZE": "2 kls",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "226",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "1",
        "STOCK_QUANTITY": "1",
        "STOCK_KEY_UNIT": "SP-A-0029",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Balancer",
        "STOCK_SIZE": "1 foot diameter",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "227",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "6",
        "STOCK_QUANTITY": "6",
        "STOCK_KEY_UNIT": "SP-A-0030",
        "STOCK_MODEL": "1 foot",
        "STOCK_NAME": "Fuel line steel tube",
        "STOCK_SIZE": "1 foot",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Rodrigo Hydraulic",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "228",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "6",
        "STOCK_QUANTITY": "6",
        "STOCK_KEY_UNIT": "SP-A-0031",
        "STOCK_MODEL": "1.2",
        "STOCK_NAME": "Fuel line steel tube",
        "STOCK_SIZE": "1`.2",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Rodrigo Hydraulic",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "229",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "6",
        "STOCK_QUANTITY": "6",
        "STOCK_KEY_UNIT": "SP-A-0032",
        "STOCK_MODEL": "1.4",
        "STOCK_NAME": "Fuel line steel tube",
        "STOCK_SIZE": "1.4",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Rodrigo Hydraulic",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "230",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "6",
        "STOCK_QUANTITY": "6",
        "STOCK_KEY_UNIT": "SP-A-0033",
        "STOCK_MODEL": "1.6",
        "STOCK_NAME": "Fuel line steel tube",
        "STOCK_SIZE": "1.6",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Rodrigo Hydraulic",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "231",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "6",
        "STOCK_QUANTITY": "6",
        "STOCK_KEY_UNIT": "SP-A-0034",
        "STOCK_MODEL": "1.7",
        "STOCK_NAME": "Fuel line steel tube",
        "STOCK_SIZE": "1.7",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Rodrigo Hydraulic",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "232",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "6",
        "STOCK_QUANTITY": "6",
        "STOCK_KEY_UNIT": "SP-A-0035",
        "STOCK_MODEL": "1.8",
        "STOCK_NAME": "Fuel line steel tube",
        "STOCK_SIZE": "1.8",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "Replaceable",
        "SUP_NAME": "Rodrigo Hydraulic",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "202",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "10",
        "STOCK_QUANTITY": "10",
        "STOCK_KEY_UNIT": "SP-A-0003",
        "STOCK_MODEL": "134A",
        "STOCK_NAME": "Freon",
        "STOCK_SIZE": "13.5 kg/8 diameter",
        "UNIT_TYPE": "Tank",
        "CON_NAME": "Refillable",
        "SUP_NAME": "Tastic",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "217",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "1",
        "STOCK_QUANTITY": "1",
        "STOCK_KEY_UNIT": "SP-A-0020",
        "STOCK_MODEL": "PKB",
        "STOCK_NAME": "Radiator",
        "STOCK_SIZE": "2 ft x 4 ft",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "Repairable",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "233",
        "STOCK_BRAND": "I-beam",
        "STOCK_CRITICAL_LEVEL": "1",
        "STOCK_QUANTITY": "1",
        "STOCK_KEY_UNIT": "SP-A-0038",
        "STOCK_MODEL": "1.5 inchx 1 ft.",
        "STOCK_NAME": "Under chassis",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "Repairable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "216",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "10",
        "STOCK_QUANTITY": "10",
        "STOCK_KEY_UNIT": "SP-A-0019",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Oil filter",
        "STOCK_SIZE": "1 liter",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "oil",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "234",
        "STOCK_BRAND": "King pin",
        "STOCK_CRITICAL_LEVEL": "1",
        "STOCK_QUANTITY": "1",
        "STOCK_KEY_UNIT": "SP-A-0039",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Under chassis",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "235",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0040",
        "STOCK_MODEL": "30 kls metal",
        "STOCK_NAME": "Propeller",
        "STOCK_SIZE": "30 kls",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "236",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "3",
        "STOCK_QUANTITY": "3",
        "STOCK_KEY_UNIT": "SP-A-0041",
        "STOCK_MODEL": "3 ft madre",
        "STOCK_NAME": "Molye",
        "STOCK_SIZE": "7 ft madre ",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "237",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "3",
        "STOCK_QUANTITY": "3",
        "STOCK_KEY_UNIT": "SP-A-0042",
        "STOCK_MODEL": "8 ft madre",
        "STOCK_NAME": "Molye",
        "STOCK_SIZE": "8 ft madre",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "238",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "3",
        "STOCK_QUANTITY": "3",
        "STOCK_KEY_UNIT": "SP-A-0043",
        "STOCK_MODEL": "4 ft tersera madre",
        "STOCK_NAME": "Molye",
        "STOCK_SIZE": "4 ft tersera madre",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "239",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "3",
        "STOCK_QUANTITY": "3",
        "STOCK_KEY_UNIT": "SP-A-0044",
        "STOCK_MODEL": "1",
        "STOCK_NAME": "dahon",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "240",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "3",
        "STOCK_QUANTITY": "3",
        "STOCK_KEY_UNIT": "SP-A-0045",
        "STOCK_MODEL": "2",
        "STOCK_NAME": "dahon",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "241",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "3",
        "STOCK_QUANTITY": "3",
        "STOCK_KEY_UNIT": "SP-A-0046",
        "STOCK_MODEL": "3",
        "STOCK_NAME": "dahon",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "242",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "3",
        "STOCK_QUANTITY": "3",
        "STOCK_KEY_UNIT": "SP-A-0047",
        "STOCK_MODEL": "4",
        "STOCK_NAME": "dahon",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "243",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "3",
        "STOCK_QUANTITY": "3",
        "STOCK_KEY_UNIT": "SP-A-0048",
        "STOCK_MODEL": "5",
        "STOCK_NAME": "dahon",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "244",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "3",
        "STOCK_QUANTITY": "3",
        "STOCK_KEY_UNIT": "SP-A-0049",
        "STOCK_MODEL": "6",
        "STOCK_NAME": "dahon",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "245",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0050",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Center bearing",
        "STOCK_SIZE": "6 inches diameter",
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "248",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "5",
        "STOCK_QUANTITY": "5",
        "STOCK_KEY_UNIT": "SP-A-0053",
        "STOCK_MODEL": "JP/ 5 sets",
        "STOCK_NAME": "Break lining",
        "STOCK_SIZE": "6 x 8",
        "UNIT_TYPE": "rear",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "249",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "12",
        "STOCK_QUANTITY": "12",
        "STOCK_KEY_UNIT": "SP-A-0054",
        "STOCK_MODEL": "1 box/12 pcs",
        "STOCK_NAME": "Break fluid",
        "STOCK_SIZE": "1 liter",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "250",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "3",
        "STOCK_QUANTITY": "3",
        "STOCK_KEY_UNIT": "SP-A-0055",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Break line flexible hore",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "251",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "6",
        "STOCK_QUANTITY": "6",
        "STOCK_KEY_UNIT": "SP-A-0056",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Hydraulic Cylinder(rear)",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "252",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0057",
        "STOCK_MODEL": "SP",
        "STOCK_NAME": "Foot bulb assembly",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "253",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0058",
        "STOCK_MODEL": "JP ",
        "STOCK_NAME": "Foot bulb assembly",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "254",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0059",
        "STOCK_MODEL": "PKB",
        "STOCK_NAME": "Foot bulb assembly",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "255",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0060",
        "STOCK_MODEL": "90 meter",
        "STOCK_NAME": "Clutch Booster",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "256",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "4",
        "STOCK_QUANTITY": "4",
        "STOCK_KEY_UNIT": "SP-A-0061",
        "STOCK_MODEL": "70 meter",
        "STOCK_NAME": "Clutch Booster",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "259",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0065",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Draggling ",
        "STOCK_SIZE": "2x8 diameter",
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "260",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "8",
        "STOCK_QUANTITY": "8",
        "STOCK_KEY_UNIT": "SP-A-0066",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Exhaust break bulb",
        "STOCK_SIZE": "1/4 kilo",
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "261",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "3",
        "STOCK_QUANTITY": "3",
        "STOCK_KEY_UNIT": "SP-A-0067",
        "STOCK_MODEL": "SP clutch lining",
        "STOCK_NAME": "Clutch assembly",
        "STOCK_SIZE": "16 diameter",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "262",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "3",
        "STOCK_QUANTITY": "3",
        "STOCK_KEY_UNIT": "SP-A-0068",
        "STOCK_MODEL": "PKB",
        "STOCK_NAME": "Clutch assembly",
        "STOCK_SIZE": "16 diameter",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "263",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "3",
        "STOCK_QUANTITY": "3",
        "STOCK_KEY_UNIT": "SP-A-0069",
        "STOCK_MODEL": "JP",
        "STOCK_NAME": "Clutch assembly",
        "STOCK_SIZE": "18 diameter",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "267",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0073",
        "STOCK_MODEL": "SP",
        "STOCK_NAME": "Pressure plate",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "268",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0074",
        "STOCK_MODEL": "JP",
        "STOCK_NAME": "Pressure plate",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "269",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0075",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Shifting level",
        "STOCK_SIZE": "1 foot length/1 inch diameter",
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "273",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0079",
        "STOCK_MODEL": "JP  ",
        "STOCK_NAME": "Accelerator cable",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "274",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0080",
        "STOCK_MODEL": "PKB",
        "STOCK_NAME": "Accelerator cable",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "276",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0082",
        "STOCK_MODEL": "SP ",
        "STOCK_NAME": "Tire rod end",
        "STOCK_SIZE": "1 set",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "277",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0083",
        "STOCK_MODEL": "PKB",
        "STOCK_NAME": "Tire rod end",
        "STOCK_SIZE": "1 set",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "278",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "1",
        "STOCK_QUANTITY": "1",
        "STOCK_KEY_UNIT": "SP-A-0084",
        "STOCK_MODEL": "PKB/SP",
        "STOCK_NAME": "Drag link",
        "STOCK_SIZE": "5.5 ft x 1 ft",
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "279",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "1",
        "STOCK_QUANTITY": "1",
        "STOCK_KEY_UNIT": "SP-A-0085",
        "STOCK_MODEL": "JP",
        "STOCK_NAME": "Drag link",
        "STOCK_SIZE": "3 ft length/1 inch diameter",
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "283",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "3",
        "STOCK_QUANTITY": "3",
        "STOCK_KEY_UNIT": "SP-A-0091",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Black sausage sealant",
        "STOCK_SIZE": "20 pcs",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Comglasco",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "284",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "5",
        "STOCK_QUANTITY": "5",
        "STOCK_KEY_UNIT": "SP-A-0092",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Mirror",
        "STOCK_SIZE": "14 x 72",
        "UNIT_TYPE": "flat glass",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Comglasco",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "285",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "7",
        "STOCK_QUANTITY": "7",
        "STOCK_KEY_UNIT": "SP-A-0093",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Mirror",
        "STOCK_SIZE": "16 x 72",
        "UNIT_TYPE": "flat glass",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Comglasco",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "286",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "3",
        "STOCK_QUANTITY": "3",
        "STOCK_KEY_UNIT": "SP-A-0094",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Wind shield",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "left and right",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Comglasco",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "287",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "5",
        "STOCK_QUANTITY": "5",
        "STOCK_KEY_UNIT": "SP-A-0095",
        "STOCK_MODEL": null,
        "STOCK_NAME": "flat framing",
        "STOCK_SIZE": "36 x 84",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Comglasco",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "288",
        "STOCK_BRAND": "Nissan",
        "STOCK_CRITICAL_LEVEL": "1",
        "STOCK_QUANTITY": "1",
        "STOCK_KEY_UNIT": "SP-A-0096",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Alternator",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "metal assembled",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Fastech",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "289",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "45",
        "STOCK_QUANTITY": "45",
        "STOCK_KEY_UNIT": "SP-A-0097",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Diode",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Fastech",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "290",
        "STOCK_BRAND": "New Era",
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0098",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Voltage Regulator",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "291",
        "STOCK_BRAND": "Nissan",
        "STOCK_CRITICAL_LEVEL": "2",
        "STOCK_QUANTITY": "2",
        "STOCK_KEY_UNIT": "SP-A-0099",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Head Light",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "292",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "10",
        "STOCK_QUANTITY": "10",
        "STOCK_KEY_UNIT": "SP-A-0100",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Signal Light",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "293",
        "STOCK_BRAND": "Nissan",
        "STOCK_CRITICAL_LEVEL": "10",
        "STOCK_QUANTITY": "10",
        "STOCK_KEY_UNIT": "SP-A-0101",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Stoplight",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "294",
        "STOCK_BRAND": "Nissan",
        "STOCK_CRITICAL_LEVEL": "10",
        "STOCK_QUANTITY": "10",
        "STOCK_KEY_UNIT": "SP-A-0102",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Passenger Light",
        "STOCK_SIZE": "1 set",
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "295",
        "STOCK_BRAND": "Led HW",
        "STOCK_CRITICAL_LEVEL": "6",
        "STOCK_QUANTITY": "6",
        "STOCK_KEY_UNIT": "SP-A-0103",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Fog light",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "296",
        "STOCK_BRAND": "Hella",
        "STOCK_CRITICAL_LEVEL": "6",
        "STOCK_QUANTITY": "6",
        "STOCK_KEY_UNIT": "SP-A-0104",
        "STOCK_MODEL": null,
        "STOCK_NAME": "Clearance light",
        "STOCK_SIZE": null,
        "UNIT_TYPE": "NULL",
        "CON_NAME": "replaceable",
        "SUP_NAME": "Casa",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "246",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "5",
        "STOCK_QUANTITY": "5",
        "STOCK_KEY_UNIT": "SP-A-0051",
        "STOCK_MODEL": "SP  /5 sets",
        "STOCK_NAME": "Break lining",
        "STOCK_SIZE": "4 x 8 ",
        "UNIT_TYPE": "front",
        "CON_NAME": "replaceable/asbestos",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }, {
        "STOCK_ID": "247",
        "STOCK_BRAND": null,
        "STOCK_CRITICAL_LEVEL": "5",
        "STOCK_QUANTITY": "5",
        "STOCK_KEY_UNIT": "SP-A-0052",
        "STOCK_MODEL": "JP/ 5 sets",
        "STOCK_NAME": "Break lining",
        "STOCK_SIZE": "5 x 4",
        "UNIT_TYPE": "front",
        "CON_NAME": "replaceable/asbestos",
        "SUP_NAME": "Jecara",
        "SUP_EMAIL": null,
        "SUP_CONTACT_NO": null,
        "SUP_ADDRESS": null,
        "isCritical": "#fbc7c7",
        "value": false,
        "qty": 0,
        "suppid": 0
    }]
}';

$output = '';
$result = mysqli_query($conn, "SELECT MAX(BATCH_NO) FROM t_spare_requisition_summary");
    $row = mysqli_fetch_array($result);
    $sum_id = $row[0];
    $new_id = $sum_id + 1;
echo $output .= $new_id;
	
// echo $output;

// foreach(array($items) as $item)
// { 
// 	 $batch_req = '
// 	  INSERT INTO `t_spare_requisition_summary` (`BATCH_NO`, `DATE_REQUESTED`, `DATE_REVISED`, `DATE_APPROVED`, `DATE_RELEASED`, `STATUS_REQ`, `REMARKS`, `REQUESTED_BY`) VALUES ("'.$item_batch_clean.'", "'.$item_date_clean.'", NULL, NULL, NULL, 1, 4, 1)
// 	  ';
// 	 $query .= '
// 	 INSERT INTO `t_spare_requisition_old_stock` (`REF_STOCK_ID`, `QUANTITY`,`STOCK_SUPPLIER`, `REF_BATCH_NO`) VALUES ("'.$item_name_clean.'", "'.$item_quan_clean.'","'.$item_supplier_clean.'","'.$item_batch_clean.'") 
// 	 ';
// 	}  
// 	if(mysqli_multi_query($conn, $batch_req) && mysqli_multi_query($conn, $query))
// 	{
// 	 echo "Success";
// 	}
// 	else 
// 	{
// 	 echo 'Error';
// 	}

$conn->close();
?>